In [1]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

In [5]:
#벡터화 연산
data = [0,1,2,3,4,5,6,7,8,9] #이건 리스트
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
x = np.array(data)
x # 이게 배열

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
2 * x #이게 벡터화 연산

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
l = [0,1,2,3,4,5,6,7,8,9]
print(2*l) #리스트 객체에 정수곱을 하면 그 정수만큼 크기가 배로 증가

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [10]:
2 * a + b

array([12, 24, 36])

In [11]:
a == 2

array([False,  True, False])

In [13]:
b > 10
#각각의 원소에 대해 연산한다고 생각, 벡터화

array([False,  True,  True])

In [29]:
#2차원 배열 만들기
c = np.array([[0,1,2], [3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
#행의 개수
len(c)

2

In [31]:
#열의 개수
len(c[0])

3

In [32]:
#연습 문제 1
c1 = np.array([[10,20,30,40],[50,60,70,80]])

In [33]:
c1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [34]:
#3차원 배열 만들기
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [35]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [36]:
#배열의 차원과 크기 알아내기 : 배열의 ndim(차원), shape(크기) 속성을 이용
#a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [37]:
#c = np.array([[0,1,2], [3,4,5]])
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [38]:
#배열의 인덱싱
a = np.array([0,1,2,3,4])
a[2]

2

In [39]:
a[-1]

4

In [40]:
a[-2]

3

In [42]:
a[-100]

IndexError: index -100 is out of bounds for axis 0 with size 5

In [43]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
a[0,0]

0

In [45]:
a[-1,-1]

5

In [46]:
#배열 슬라이싱
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
a[0,:]

array([0, 1, 2, 3])

In [48]:
a[:,1]

array([1, 5])

In [49]:
a[1,1:]

array([5, 6, 7])

In [50]:
a[:2, :2] # : 이 앞에 있으면 ~까지 + 미만 (~를 포함하지않음), 뒤에 있으면 ~부터 + 이상 (~를 포함)

array([[0, 1],
       [4, 5]])

In [51]:
#연습문제 2
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
# 값 7을 인덱싱
m[1,2]

7

In [52]:
#값 14를 인덱싱
m[2,-1]

14

In [56]:
#배열 [6,7]을 슬라이싱
m[1, 1:3]

array([6, 7])

In [57]:
#배열 [7,12]를 슬라이싱
m[1:, 2]

array([ 7, 12])

In [59]:
#배열 [[3,4],[8,9]]를 슬라이싱
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [60]:
#배열 인덱싱, 퀴리 기능을 수행
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [63]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [64]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [65]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [66]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

In [67]:
idx = np.array([0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2])
a[idx] # 배열 a의 범위에만 있다면 반환할 인덱스 배열의 크기는 배열보다 더 커도 상관없음

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [68]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
a[:, [True,False,False,True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [70]:
a[[2,0,1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [72]:
#연습문제 3
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
#이 배열에서 3의 배수를 찾아라
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [73]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [76]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])