In [2]:
#넘파이의 자료형
import numpy as np
x = np.array([1,2,3])
x.dtype

dtype('int64')

In [3]:
x = np.array([1.0, 2.0, 3.0])

In [4]:
x.dtype

dtype('float64')

In [5]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

In [ ]:
# dtype 접두사 |     설명     | 사용 예
# b              booelan     b(참 혹은 거짓)
# i               int        i8(64bit)
# u            unsigned int  u8(64bit)
# f              부동소수점     f8(64bit)
# c            복수 부동소수점   c16(128bit)
# O               object     o(객체에 대한 포인터)
# S             바이트 문자열    S24(24글자)
# U            유니코드 문자열   U24(24 유니코드 글자)

In [6]:
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [7]:
x[0] + x[1]

3.0

In [9]:
x = np.array([1,2,3], dtype='U')
x.dtype

dtype('<U1')

In [10]:
x[0] + x[1]

'12'

In [11]:
#Inf와 NaN
np.array([0,1,-1,0]) / np.array([1,0,0,0])

/Users/mundayeon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/Users/mundayeon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([  0.,  inf, -inf,  nan])

In [12]:
np.log(0)

/Users/mundayeon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [13]:
np.exp(-np.inf)

0.0

In [14]:
#배열 생성
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [15]:
b = np.zeros((2,3)) # 이건 튜플을 사용해 다차원 배열 생성
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [17]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE" # 선언할때 U4로 선언해 크기가 더 크게 초기화했으므로 짤림
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [18]:
e = np.ones((2,3,4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
f = np.ones_like(b, dtype="f") #다른 배열과 같은 크기의 배열을 생성하고 싶을 때
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [20]:
g = np.empty((4,3))
g

array([[-2.31584178e+077, -2.31584178e+077,  2.96439388e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [-2.31584178e+077, -2.31584178e+077,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  8.34402697e-309]])

In [21]:
np.arange(10) # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(3,21,2) #시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [24]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [25]:
np.linspace(0.1,1,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [26]:
#전치 연산 : 행과 열을 바꾸는 작업
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
A.T # tranpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
#배열의 크기 변형
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a.reshape(3,-1) #-1은 튜플 중 정해진 원소를 토대로 계산하여 적당한 값이 들어감

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [32]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [33]:
#다차원 배열을 무조건 1차원으로 만들기 위해
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
#주의할 점 : 행, 열이 (5,1)인 배열과 (1,5)인 배열은 다른 객체이다
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [36]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [37]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [38]:
#1차원 증가시키는 경우
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [39]:
#배열 연결
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [41]:
np.hstack([a1,a2]) # 행의 수가 같은 두 개 이상의 배열을 옆으로 연결해, 열의 수가 더 많은 배열로

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [42]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.vstack([b1, b2]) # 행의 수가 더 많은 배열로

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.dstack([c1, c2]) #제 3의 축, 깊이 방향으로 배열을 합친다. 가장 안쪽의 원소의 차원이 증가

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [49]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [51]:
c = np.stack([c1, c2]) #dstack의 기능을 확장 : 사용자가 지정한 차원
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [52]:
c.shape

(2, 3, 4)

In [53]:
c = np.stack([c1, c2], axis=1) #axis 인수가 1이면 두번째 차원으로 새로운 차원이 삽입됨.
c                              #즉, shape 변화는 2개의 (3x4) -> 1개의 (3x2x4)

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [54]:
c.shape

(3, 2, 4)

In [56]:
#r_ 메서드 : hstack명령과 비슷하게 배열을 좌우로 연결. 소괄호를 사용하지않고 대괄호를 사용. 이런 특수 메서드를 인덱서라고 함!
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [57]:
#c_ 메소드 : 배열의 차원을 증가시킨 후 좌우로 연결
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
#tile : 동일한 배열을 반복하여 연결
a = np.array([[0,1,2], [3,4,5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [59]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
#2차원 그리드 포인트 생성 .. 나중에 보고싶으면 참고하면 될 듯 ...! ㅎㅎ
# https://datascienceschool.net/01%20python/03.02%20배열의%20생성과%20변형.html