In [2]:
#벡터화 연산
import numpy as np
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [3]:
x

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [4]:
y

array([10001, 10002, 10003, ..., 19998, 19999, 20000])

In [5]:
# %%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

In [6]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [7]:
z = x + y # 벡터연산으로 for문을 쓰지않고 연산 하나로 !

In [8]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [10]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a==b

array([False,  True, False,  True])

In [11]:
a>=b

array([False,  True,  True,  True])

In [12]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [13]:
np.all(a==b)

False

In [14]:
np.all(a==c) # all : 해당 배열의 원소가 전부 같은지

True

In [15]:
# 지수, 로그도 벡터화 연산 지원
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [16]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [17]:
10 ** a

array([    1,    10,   100,  1000, 10000])

In [18]:
np.log(a+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [19]:
#스칼라와 벡터 / 행렬의 곱셈
x = np.arange(10)

In [20]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [22]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [24]:
#브로드캐스팅
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [25]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [26]:
x + y

array([1, 2, 3, 4, 5])

In [27]:
x + 1

array([1, 2, 3, 4, 5])

In [28]:
x + 1

array([1, 2, 3, 4, 5])

In [29]:
x + 2

array([2, 3, 4, 5, 6])

In [30]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [31]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [32]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [33]:
y = np.arange(3)
y

array([0, 1, 2])

In [34]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

# 차원 축소 연산

In [35]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [36]:
np.sum(x)

10

In [37]:
x.sum()

10

In [38]:
x = np.array([1,3,2])

In [39]:
x.min()

1

In [40]:
x.max()

3

In [41]:
x.argmin() #최소값의 위치

0

In [42]:
x.argmax() # 최댓값의 위치

1

In [43]:
x = np.array([1,2,3,1])
x.mean()

1.75

In [44]:
np.median(x)

1.5

In [45]:
np.all([True, True, False])

False

In [46]:
np.any([True, True, False])

True

In [47]:
a = np.zeros((100, 100), dtype = np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [48]:
np.any(a!=0)

False

In [49]:
np.all(a==a)

True

In [50]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b) & (b <= c)).all()

True

In [51]:
x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [52]:
x.sum()

6

In [53]:
x.sum(axis=0) # 열 합계

array([3, 3])

In [54]:
x.sum(axis=1) # 행 합계

array([2, 4])

# 정렬

In [55]:
a = np.array([[4, 3, 5, 7], [1, 12, 11, 9], [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [56]:
np.sort(a) #axis = -1또는 1과 동일, 배열 내(행)에서만 정렬

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [57]:
np.sort(a, axis=0) # 같은 열에 있는 원소들끼리 정렬

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [58]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [59]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a) # 자료를 정리하지않고 순서만 알고싶을때
j

array([2, 3, 1, 0])

In [60]:
a[j]

array([12, 25, 38, 42])

In [61]:
np.sort(a)

array([12, 25, 38, 42])