# 시드 설정하기

In [2]:
import numpy as np
np.random.seed(0)

In [3]:
np.random.rand(5) # 0~1의 난수를 인수의 크기만큼

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [4]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [5]:
np.random.rand(0) # 시드를 다시 0으로 설정

array([], dtype=float64)

In [6]:
np.random.rand(5)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [7]:
np.random.rand(10)

array([0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194])

In [8]:
np.random.rand(10)

array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ])

In [9]:
# 아까랑 같은 숫자ㅏ가 나온다고 했는데 다 다른 난수가 생성된다 ....

# 데이터의 순서 바꾸기

In [10]:
x = np.arange(10)

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.shuffle(x)
x

array([5, 0, 4, 2, 3, 6, 7, 9, 1, 8])

# 데이터 샘플링

In [13]:
# numpy.random.choice(a, size = None, replace = True, p = None)
# a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
# size : 정수, 샘플 숫자
# replace : boolean, True이면 한 번 선택한 데이터를 다시 선택 가능
# p : 배열, 각 데이터가 선택될 수 있는 확률
np.random.choice(5, 5, replace=False) # same as 'shuffle'

array([4, 1, 2, 0, 3])

In [14]:
np.random.choice(5, 3, replace=False)

array([3, 0, 2])

In [15]:
np.random.choice(5, 10)

array([3, 4, 4, 4, 3, 4, 4, 4, 0, 4])

In [16]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 선택 확률을 다르게

array([2, 2, 2, 3, 2, 2, 2, 3, 0, 3])

# 난수 생성

In [17]:
np.random.rand(10)

array([0.09609841, 0.97645947, 0.4686512 , 0.97676109, 0.60484552,
       0.73926358, 0.03918779, 0.28280696, 0.12019656, 0.2961402 ])

In [18]:
np.random.rand(3, 5)

array([[0.11872772, 0.31798318, 0.41426299, 0.0641475 , 0.69247212],
       [0.56660145, 0.26538949, 0.52324805, 0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895, 0.66741038, 0.13179786, 0.7163272 ]])

In [19]:
np.random.randn(10) # 표준 정규 분포(기댓값이 0, 표준편차 1)를 따르는 난수를 생성

array([-0.87079715, -0.57884966, -0.31155253,  0.05616534, -1.16514984,
        0.90082649,  0.46566244, -1.53624369,  1.48825219,  1.89588918])

In [20]:
np.random.randn(3, 5)

array([[ 1.17877957, -0.17992484, -1.07075262,  1.05445173, -0.40317695],
       [ 1.22244507,  0.20827498,  0.97663904,  0.3563664 ,  0.70657317],
       [ 0.01050002,  1.78587049,  0.12691209,  0.40198936,  1.8831507 ]])

In [21]:
np.random.randint(10, size=10)

array([9, 6, 5, 7, 8, 8, 9, 2, 8, 6])

In [22]:
np.random.randint(10, 20, size = 10)

array([16, 19, 11, 16, 18, 18, 13, 12, 13, 16])

In [23]:
np.random.randint(10, 20, size=(3, 5))

array([[13, 16, 15, 17, 10],
       [18, 14, 16, 15, 18],
       [12, 13, 19, 17, 15]])

# 정수 데이터 카운팅

In [24]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [25]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [26]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [27]:
count

array([2, 2, 1])

In [28]:
np.bincount([1, 1, 2, 2, 3], minlength=6)

array([0, 2, 2, 1, 0, 0])